services:
  - type: web
    name: irctc-clone
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html